hackpy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

urlpatterns += staticfiles_urlpatterns()

mainapp/urls.py
from django.urls import path
from . import views

app_name = "mainapp"

urlpatterns = [
    path('', views.home, name = "home"),
    # path('<str:city>/',views.view_hack, name = "hackathon"),
    path('login/',views.login_view, name = "login"),
    path('logout/', views.logout_view, name = "logout"),
    path('register/', views.register_view, name = "register"),
    path('about/', views.about, name="about"),
    path('<str:city>/',views.view_hack, name = "hackathon"),
    
]

mainapp/models.py
from django.db import models

class Hackathons(models.Model):
    title = models.CharField(max_length=50)
    url = models.CharField(max_length=100)

    def __str__(self):
        return self.title + str(self.url)

class Cities(models.Model):
    city = models.CharField(max_length=50)

    def __str__(self):
        return self.city

mainapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.decorators import login_required
from .models import Hackathons,Cities

@login_required(login_url="mainapp:login")
def home(request):
    cities = Cities.objects.all()
    return render(request,'mainapp/home.html',{'cities':cities, 'home': True, })


def register_view(request):
    if request.method == 'POST' :
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect("mainapp:home")
    else:
        form = UserCreationForm()
    return render(request, 'mainapp/register.html', {'form':form})

def login_view(request):
    if request.method == "POST" :
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect("mainapp:home")
    else:
        form = AuthenticationForm()
    return render(request,"mainapp/login.html",{'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect("mainapp:home")

def view_hack(request,city):
    hackathons = Hackathons.objects.all()
    return render(request, 'mainapp/hackathons.html', {'hackathons': hackathons, 'city': city})

def about(request):
    return render(request, 'mainapp/about.html', {'about': True })

mainapp/templates/mainapp/about.html
{%extends 'mainapp/base.html'%}

{%block content%}
<div class="jumbotron">
    <h1 class="display-3">About us</h1>
    <p class="lead text-info">This project was created by</p>
</div>

  <div class="container">
      <div class="row">
        <div class="col-md-4">
            <div class="card">
                <!-- <img class="card-img-top" src="/images/pathToYourImage.png" alt="Card image cap"> -->
                <div class="card-body">
                  <h4 class="card-title">Rebecca Dias</h4>
                  <a href="https://github.com/rebeccadias" class="btn btn-primary">Github</a>
                </div>
              </div>
          </div>
          <div class="col-md-4">
            <div class="card">
                <!-- <img class="card-img-top" src="/images/pathToYourImage.png" alt="Card image cap"> -->
                <div class="card-body">
                  <h4 class="card-title">Alan Dsilva</h4>
                  <a href="https://github.com/DeathBringer269" class="btn btn-primary">Github</a>
                </div>
              </div>
          </div>
          <div class="col-md-4">

          </div>
      </div>
  </div>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'main.css' %}">


  <title>Hackpy</title>
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-header fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4 font-weight-bold" href="{% url 'mainapp:home' %}">HackPY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link {% if home %}active{% endif %}" href="{% url 'mainapp:home' %}">Home</a>
            <a class="nav-item nav-link {% if about %}active{% endif %}" href="{% url 'mainapp:about' %}">About</a>
          </div>

          <div class="navbar-nav">
              <a class="nav-item nav-link active" href="{% url 'mainapp:login' %}">Login</a>
              <a class="nav-item nav-link active" href="{% url 'mainapp:register' %}">Register</a>
          </div>
        </div>
      </div>
    </nav>
  </header>



  {% block content %}{% endblock %}
  

  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

mainapp/templates/mainapp/hackathons.html
{%extends 'mainapp/base.html'%}

{%block content%}
<div class="container">
    <legend class="border-bottom mb-4 font" style="text-align: center">{{city}}</legend>
    <ul class="list-group">
        {% for hackathon in hackathons %}
              <a href="{{ hackathon.url }}">
                   <li class="list-group-item">
                    {{hackathon.title}}
              </li> </a>
          {%endfor%}
      </ul>
      </div>
{%endblock%}

mainapp/templates/mainapp/home.html
{%extends 'mainapp/base.html'%}

{%block content%}

<div class="jumbotron">
    <h1 class="display-3">Welcome to HackPY</h1>
    <p class="lead text-info">Select a city to get started</p>
</div>
<ul class="list-group">
  {%for c in cities %}
        <a href="{{c.city}}">
             <li class="list-group-item">
                {{c.city}}
        </li> </a>
    {%endfor%}
</ul>
    
{%endblock%}

mainapp/templates/mainapp/login.html
{%extends 'mainapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{%block title%}Login{%endblock%}

    {%block content%}
        
    <div class="container align-center">
        <div class="row">
            <div class="col-md-3 col-sm-1"></div>
            <div class="col-md-6 col-sm-10">
                <div class="content-section shadow-lg">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4 font">Sign in</legend>
                            {{ form|crispy }}
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-primary justify-content-end" type="Submit">Sign up</button>
                        </div>
                    </form>
                    <div class="border-top pt-3">
                        <small class="text-muted">Need an account? <a class="ml-2" href="{% url 'mainapp:register' %}">Sign up</a></small>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-1"></div>
        </div>
    </div>
    {%endblock%}

mainapp/templates/mainapp/register.html
{%extends 'mainapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{%block content%}
<div class="container align-center">
	<div class="row">
		<div class="col-md-3 col-sm-1"></div>
		<div class="col-md-6 col-sm-10">
			<div class="content-section shadow-lg">
				<form method="POST">
					{% csrf_token %}
					<fieldset class="form-group">
						<legend class="border-bottom mb-4">Sign up</legend>
						{{ form|crispy }}
					</fieldset>
					<div class="form-group d-flex justify-content-end">
						<button class="btn btn-outline-info" type="Submit">Sign up</button>
					</div>
				</form>
				<div class="border-top pt-3">
					<small class="text-muted">Already have an account? <a class="ml-2" href="{% url 'mainapp:login' %}">Sign in</a></small>
				</div>
			</div>
		</div>
		<div class="col-md-3 col-sm-1"></div>
	</div>

</div>
{%endblock%}